version: '3'

services:
  db:
    image: postgres
    container_name: postgres-local
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "numsey"
    ports:
      - "5432:5432"
    volumes:
       - postgres_orm:/var/lib/postgresql/data

volumes:
  postgres_orm: