version: '3'

services:
  db-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "numsey"
    ports:
      - "5432:5432"
    volumes:
       - postgres_orm:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
      
  db-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "emotton@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "numsey"
    ports:
      - "16543:80"
    depends_on:
      - db-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge